Added bash script for monitoring sonarqube quality gates

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -116,6 +116,16 @@ jobs:
           -Dsonar.host.url=https://sonarcloud.io \
           -Dsonar.login=${SONARQUBE_TOKEN} ${SONAR_SCANNER_OPTS_CUSTOM}
 
+           curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=mdgriffin_devops-project > sonarqube_result.json
+
+           if cat sonarqube_result.json | grep -Poq '"ERROR"'
+           then
+               echo 'Failed Quality Gates'
+               exit 1
+           else
+               echo 'Passed Quality Gates'
+               exit 0
+           fi
   deploy:
     docker:
     - image: google/cloud-sdk
